### ISSUE TITLE
Is it possible to host specific channel on d.tube?

### ISSUE THREAD

**Issue by chikiuso** [Johnn3y/ipfs-pin-steem#1]
Hi, Is it possible to host specific channel on d.tube? Thanks.

**Comment by Johnn3y** [comment]
Now you can (experimental)
You need `beem` API-Library (`pip install ipfs-pin-steem[beem]`)
```
ipfs-pin-steem account
```
This will not work in Version 1.0.6:
```
ipfs-pin-steem d.tube/c/account
```
